easy_admin:
    site_name: '<em style="font-size: 100%;">AppPizza</em>'
    user:
        name_property_path: 'nomPrenomComplet'
    entities:
        Pizza:
            class: App\Entity\Pizza
            label: 'Gestion des pizzas'
        Utilisateur:
            class: App\Entity\Utilisateur
            label: 'Gestion des utilisateurs'
            controller: App\Controller\Admin\Utilisateur\UtilisateurAdminController
            form:
                fields:
                    - { property: 'email' }
                    - { property: 'plainPassword', type: 'password', label: 'Mot de passe', type_options: { required: false }}
                    - { property: 'prenom' }
                    - { property: 'nom' }
