easy_admin:
    site_name: '<em style="font-size: 100%;">AppPizza</em>'
    user:
        name_property_path: 'nomPrenomComplet'
    entities:
        # List the entity class name you want to manage
        - App\Entity\Pizza
