app_connexion:
    path: /connexion
    controller: App\Controller\SecurityController::login

app_deconnexion:
    path: /deconnexion
    controller: App\Controller\SecurityController::logout

front_liste_pizza_index:
    path: /
    controller: App\Controller\Front\ListePizzaController::index
