app_connexion:
    path: /connexion
    controller: App\Controller\SecurityController::login

app_deconnexion:
    path: /deconnexion
    controller: App\Controller\SecurityController::logout

front_liste_pizza_index:
    path: /
    controller: App\Controller\Front\ListePizzaController::index

front_ajouter_pizza_au_panier:
    path: /ajouter-pizza-au-panier
    controller: App\Controller\Front\ListePizzaController::ajouterPizzaAuPanier
    methods: POST

front_commande_pizza_recapitulatif:
    path: /commande/recapitulatif
    controller: App\Controller\Front\CommandePizzaController::recapitulatif

front_commande_pizza_vider_panier:
    path: /commande/vider-panier
    controller: App\Controller\Front\CommandePizzaController::viderPanier

front_commande_pizza_infos_client:
    path: /commande/informations-clients
    controller: App\Controller\Front\CommandePizzaController::informationsClient

front_commande_pizza_infos_livraison:
    path: /commande/informations-livraison
    controller: App\Controller\Front\CommandePizzaController::informationsLivraison

front_commande_pizza_termine:
    path: /commande/termine
    controller: App\Controller\Front\CommandePizzaController::termine
